package generator

import (
	"encoding/json"
	"fmt"
	"net/http"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"infernosim/pkg/contract"
	"infernosim/pkg/grpcsim"
	"infernosim/pkg/matcher"
	"infernosim/pkg/scenario"
	"infernosim/pkg/simtemplate"

	"gopkg.in/yaml.v3"
)

type ReplayConfig struct {
	Matching  matcher.Config     `yaml:"matching,omitempty"`
	Templates simtemplate.Config `yaml:"templates,omitempty"`
	Scenarios []scenario.Config  `yaml:"scenarios"`
}

func FromOpenAPI(path string) ([]byte, error) {
	validator, err := contract.Load(path)
	if err != nil {
		return nil, err
	}
	document := validator.Document()
	config := ReplayConfig{
		Templates: simtemplate.Config{Seed: "infernosim-generated"},
		Scenarios: []scenario.Config{{
			Name:         "openapi-generated",
			InitialState: "ready",
		}},
	}
	paths := make([]string, 0, len(document.Paths))
	for path := range document.Paths {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, pathTemplate := range paths {
		for _, operation := range operations(document.Paths[pathTemplate]) {
			status, response, ok := preferredResponse(operation.operation.Responses)
			if !ok {
				continue
			}
			headers := map[string][]string{}
			body := ""
			if media, contentType, ok := preferredMedia(response.Content); ok {
				headers["Content-Type"] = []string{contentType}
				example := schemaExample(media.Schema, document.Components.Schemas, make(map[string]bool))
				if encoded, marshalErr := json.Marshal(example); marshalErr == nil {
					body = string(encoded)
				}
			}
			name := operation.operation.OperationID
			if name == "" {
				name = strings.ToLower(operation.method) + "-" + sanitizeName(pathTemplate)
			}
			config.Scenarios[0].Steps = append(config.Scenarios[0].Steps, scenario.Step{
				Name:  name,
				State: "ready",
				Match: matcher.Rule{
					Name:      name,
					Methods:   []string{operation.method},
					PathRegex: openAPIPathRegex(pathTemplate),
				},
				Response: scenario.Response{
					Status:  status,
					Headers: headers,
					Body:    body,
				},
			})
		}
	}
	if len(config.Scenarios[0].Steps) == 0 {
		return nil, fmt.Errorf("OpenAPI document contains no operations with responses")
	}
	return marshalConfig(config)
}

func FromProtobuf(cfg grpcsim.Config) ([]byte, error) {
	registry, err := grpcsim.Load(cfg)
	if err != nil {
		return nil, err
	}
	config := ReplayConfig{
		Matching:  matcher.Config{GRPC: cfg},
		Templates: simtemplate.Config{Seed: "infernosim-generated"},
		Scenarios: []scenario.Config{{
			Name:         "protobuf-generated",
			InitialState: "ready",
		}},
	}
	for _, method := range registry.Methods() {
		example, err := registry.ResponseExample(method.Path)
		if err != nil {
			return nil, err
		}
		config.Scenarios[0].Steps = append(config.Scenarios[0].Steps, scenario.Step{
			Name:  sanitizeName(strings.TrimPrefix(method.Path, "/")),
			State: "ready",
			Match: matcher.Rule{
				Methods:    []string{http.MethodPost},
				PathRegex:  "^" + regexp.QuoteMeta(method.Path) + "$",
				GRPCMethod: method.Path,
			},
			Response: scenario.Response{
				Status:       http.StatusOK,
				Headers:      map[string][]string{"Content-Type": {"application/grpc"}},
				GRPCStatus:   "OK",
				ProtobufType: method.OutputType,
				ProtobufJSON: example,
			},
		})
	}
	return marshalConfig(config)
}

func marshalConfig(config ReplayConfig) ([]byte, error) {
	data, err := yaml.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("marshal generated replay configuration: %w", err)
	}
	header := "# Generated by InfernoSIM. Review examples and state transitions before production use.\n"
	return append([]byte(header), data...), nil
}

type namedOperation struct {
	method    string
	operation *contract.Operation
}

func operations(item contract.PathItem) []namedOperation {
	values := []namedOperation{
		{http.MethodGet, item.Get},
		{http.MethodPost, item.Post},
		{http.MethodPut, item.Put},
		{http.MethodPatch, item.Patch},
		{http.MethodDelete, item.Delete},
		{http.MethodHead, item.Head},
		{http.MethodOptions, item.Options},
		{http.MethodTrace, item.Trace},
	}
	var out []namedOperation
	for _, value := range values {
		if value.operation != nil {
			out = append(out, value)
		}
	}
	return out
}

func preferredResponse(responses map[string]contract.Response) (int, contract.Response, bool) {
	var statuses []int
	for key := range responses {
		status, err := strconv.Atoi(key)
		if err == nil && status >= 200 && status < 300 {
			statuses = append(statuses, status)
		}
	}
	sort.Ints(statuses)
	if len(statuses) > 0 {
		status := statuses[0]
		return status, responses[strconv.Itoa(status)], true
	}
	for key, response := range responses {
		if strings.EqualFold(key, "2XX") {
			return http.StatusOK, response, true
		}
	}
	if response, ok := responses["default"]; ok {
		return http.StatusOK, response, true
	}
	return 0, contract.Response{}, false
}

func preferredMedia(content map[string]contract.MediaType) (contract.MediaType, string, bool) {
	if media, ok := content["application/json"]; ok {
		return media, "application/json", true
	}
	var names []string
	for name := range content {
		names = append(names, name)
	}
	sort.Strings(names)
	if len(names) == 0 {
		return contract.MediaType{}, "", false
	}
	return content[names[0]], names[0], true
}

func schemaExample(schema *contract.Schema, components map[string]*contract.Schema, resolving map[string]bool) any {
	if schema == nil {
		return map[string]any{}
	}
	if schema.Ref != "" {
		const prefix = "#/components/schemas/"
		name := strings.TrimPrefix(schema.Ref, prefix)
		if !strings.HasPrefix(schema.Ref, prefix) || resolving[name] {
			return map[string]any{}
		}
		resolving[name] = true
		value := schemaExample(components[name], components, resolving)
		delete(resolving, name)
		return value
	}
	if len(schema.Enum) > 0 {
		return schema.Enum[0]
	}
	switch schemaType(schema.Type) {
	case "object":
		value := make(map[string]any)
		names := make([]string, 0, len(schema.Properties))
		for name := range schema.Properties {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			value[name] = schemaExample(schema.Properties[name], components, resolving)
		}
		return value
	case "array":
		return []any{schemaExample(schema.Items, components, resolving)}
	case "integer":
		return 1
	case "number":
		return 1.0
	case "boolean":
		return true
	case "null":
		return nil
	default:
		return "example"
	}
}

func schemaType(value any) string {
	switch typed := value.(type) {
	case string:
		return typed
	case []any:
		for _, item := range typed {
			if text, ok := item.(string); ok && text != "null" {
				return text
			}
		}
	}
	return ""
}

func openAPIPathRegex(path string) string {
	var expression strings.Builder
	expression.WriteByte('^')
	for index := 0; index < len(path); {
		if path[index] == '{' {
			end := strings.IndexByte(path[index:], '}')
			if end >= 0 {
				expression.WriteString(`[^/]+`)
				index += end + 1
				continue
			}
		}
		expression.WriteString(regexp.QuoteMeta(string(path[index])))
		index++
	}
	expression.WriteByte('$')
	return expression.String()
}

func sanitizeName(value string) string {
	value = strings.Trim(value, "/")
	value = regexp.MustCompile(`[^a-zA-Z0-9._-]+`).ReplaceAllString(value, "-")
	if value == "" {
		return "root"
	}
	return value
}
